# Generated by Django 2.2.4 on 2021-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
